### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by GrishaKirilin** [pulsar-edit/github#33]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### Description

I checked the diffs before committing and then committed the changes, leaving the diffs tab open. After committing, that tab was empty. The next morning, I found the following error.

### Versions

**Pulsar**: 1.106.0 x64
**Electron**: 12.2.3
**OS**: Ubuntu 22.04.2
**Thrown From**: [github](https://github.com/pulsar-edit/github) package 0.36.16

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /opt/Pulsar/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1323

TypeError: Cannot read property 'split' of null
    at Diff.lineDiff.tokenize (/app.asar/node_modules/text-buffer/node_modules/diff/lib/diff/line.js:22:32)
    at Diff.diff (/app.asar/node_modules/text-buffer/node_modules/diff/lib/diff/base.js:36:39)
    at Object.diffLines (/app.asar/node_modules/text-buffer/node_modules/diff/lib/diff/line.js:47:19)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:805:29
    at TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1320:16)
    at TextBuffer.setTextViaDiff (/app.asar/node_modules/text-buffer/lib/text-buffer.js:800:10)
    at CommitController.componentDidUpdate (/app.asar/node_modules/github/lib/controllers/commit-controller.js:106:30)
    at commitLifeCycles (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22117:22)
    at commitLayoutEffects (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25344:7)
    at HTMLUnknownElement.callCallback (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:385:16)
    at invokeGuardedCallback (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:440:31)
    at commitRootImpl (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25082:9)
    at unstable_runWithPriority (/app.asar/node_modules/scheduler/cjs/scheduler.development.js:697:12)
    at /app.asar/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
    at commitRoot (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24922:3)
    at finishSyncRender (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24329:3)
    at performSyncWorkOnRoot (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24307:9)
    at /app.asar/node_modules/react-dom/cjs/react-dom.development.js:12199:24
    at unstable_runWithPriority (/app.asar/node_modules/scheduler/cjs/scheduler.development.js:697:12)
    at /app.asar/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
    at flushSyncCallbackQueueImpl (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12194:7)
    at flushSyncCallbackQueue (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12182:3)
    at scheduleUpdateOnFiber (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23709:9)
    at Object.enqueueSetState (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13994:5)
    at ObserveModel.Component.setState (/app.asar/node_modules/react/cjs/react.development.js:325:16)
    at ModelObserver.didUpdate (/app.asar/node_modules/github/lib/views/observe-model.js:21:14)
    at ModelObserver._refreshModelData (/app.asar/node_modules/github/lib/models/model-observer.js:58:14)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
choose-pane 0.8.0 
clang-format 2.0.8 
dark-one-dark-syntax 2.3.0 
easy-motion-redux 1.3.3 
file-icons 2.1.47 
git-blame 1.8.0 
hey-pane 1.2.0 
ide-ccls 0.3.0 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
move-tab-or-split 1.1.1 
pristine-ui 1.1.11 
project-manager 3.3.8 
rainbow-csv 1.4.0 
split-diff 1.6.1 
todo-show 2.3.2 
```

### Pulsar version

1.106.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu 22.04.2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Not reproducible.

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this!

**Comment by GrishaKirilin** [comment]
It seems that the error appears every time I do (some kind of?) rebase with the directory open in the editor. I will try to reproduce the error.

**Comment by nick-tripp** [comment]
Also hitting this issue

### Versions

**Pulsar**: 1.114.0 arm64
**Electron**: 12.2.3
**OS**: macOS 14.3.1
**Thrown From**: [github](https://github.com/pulsar-edit/github) package 0.36.20


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1323

TypeError: Cannot read property 'split' of null
    at Diff.lineDiff.tokenize (/app.asar/node_modules/text-buffer/node_modules/diff/lib/diff/line.js:22:32)
    at Diff.diff (/app.asar/node_modules/text-buffer/node_modules/diff/lib/diff/base.js:36:39)
    at Object.diffLines (/app.asar/node_modules/text-buffer/node_modules/diff/lib/diff/line.js:47:19)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:805:29
    at TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1320:16)
    at TextBuffer.setTextViaDiff (/app.asar/node_modules/text-buffer/lib/text-buffer.js:800:10)
    at CommitController.componentDidUpdate (/app.asar/node_modules/github/lib/controllers/commit-controller.js:106:30)
    at commitLifeCycles (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22117:22)
    at commitLayoutEffects (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25344:7)
    at HTMLUnknownElement.callCallback (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:385:16)
    at invokeGuardedCallback (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:440:31)
    at commitRootImpl (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25082:9)
    at unstable_runWithPriority (/app.asar/node_modules/scheduler/cjs/scheduler.development.js:697:12)
    at /app.asar/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
    at commitRoot (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24922:3)
    at finishSyncRender (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24329:3)
    at performSyncWorkOnRoot (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24307:9)
    at /app.asar/node_modules/react-dom/cjs/react-dom.development.js:12199:24
    at unstable_runWithPriority (/app.asar/node_modules/scheduler/cjs/scheduler.development.js:697:12)
    at /app.asar/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
    at flushSyncCallbackQueueImpl (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12194:7)
    at flushSyncCallbackQueue (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12182:3)
    at scheduleUpdateOnFiber (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23709:9)
    at Object.enqueueSetState (/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13994:5)
    at ObserveModel.Component.setState (/app.asar/node_modules/react/cjs/react.development.js:325:16)
    at ModelObserver.didUpdate (/app.asar/node_modules/github/lib/views/observe-model.js:21:14)
    at ModelObserver._refreshModelData (/app.asar/node_modules/github/lib/models/model-observer.js:58:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Commands

```
     -1:06.4.0 intentions:highlight (input.hidden-input)
     -1:06.4.0 find-and-replace:show (input.hidden-input)
     -1:04.8.0 core:confirm (input.hidden-input)
     -0:50.4.0 intentions:highlight (input.hidden-input)
  2x -0:48 core:move-right (input.hidden-input)
  2x -0:47.4.0 core:backspace (input.hidden-input)
 10x -0:46.3.0 core:move-left (input.hidden-input)
     -0:44.6.0 core:backspace (input.hidden-input)
     -0:43.4.0 intentions:highlight (input.hidden-input)
     -0:42.6.0 editor:select-to-end-of-word (input.hidden-input)
     -0:40.4.0 intentions:highlight (input.hidden-input)
     -0:40.2.0 core:save (input.hidden-input)
     -0:37.2.0 core:backspace (input.hidden-input)
     -0:36.6.0 intentions:highlight (input.hidden-input)
     -0:36.6.0 github:commit (input.hidden-input)
     -0:22.9.0 github:pull (span.)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-inline-blame 0.0.10 
busy-signal 2.0.1 
intentions 2.1.1 
language-cmake-2 1.1.1 
language-jenkinsfile 0.1.1 
linter 3.4.0 
linter-flake8 2.4.0 
linter-pylint 2.1.1 
linter-ui-default 3.4.1 
multi-cursor 3.0.0 
```
