### ISSUE TITLE
Git package throwing multiple errors when enabled

### ISSUE THREAD

**Issue by ljsinclair** [pulsar-edit/github#5]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Github package has failed to work since the final install of atom editor.
Problem has continued with Pulsar editor

github package Version: 0.36.11 (installed with Pulsar edit)

Generates multiple errors when package is disabled then enabled:

Uncaught Error: Emitter has been disposed
C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:137
[Hide Stack Trace](https://github.com/pulsar-edit/github/issues/new?assignees=&labels=bug%2Ctriage&template=bug-report.yml#)
Error: Emitter has been disposed
    at Emitter.on (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:137:15)
    at Repository.onDidUpdate (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\github\dist\models\repository.js:137:25)
    at GitTabHeaderController.componentDidUpdate (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\github\dist\controllers\git-tab-header-controller.js:108:38)
    at commitLifeCycles (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22117:22)
    at commitLayoutEffects (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25344:7)
    at HTMLUnknownElement.callCallback (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:385:16)
    at invokeGuardedCallback (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:440:31)
    at commitRootImpl (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25082:9)
    at unstable_runWithPriority (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:697:12)
    at runWithPriority$2 (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12149:10)
    at commitRoot (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24922:3)
    at finishSyncRender (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24329:3)
    at performSyncWorkOnRoot (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24307:9)
    at C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12199:24
    at unstable_runWithPriority (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:697:12)
    at runWithPriority$2 (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12149:10)
    at flushSyncCallbackQueueImpl (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12194:7)
    at flushSyncCallbackQueue (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12182:3)
    at scheduleUpdateOnFiber (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23709:9)
    at updateContainer (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27103:3)
    at legacyRenderSubtreeIntoContainer (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27544:5)
    at Object.render (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27608:10)
    at GithubPackage.renderFn (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\github\dist\github-package.js:180:32)
    at GithubPackage.rerender (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\github\dist\github-package.js:347:10)
    at GithubPackage.consumeStatusBar (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\github\dist\github-package.js:396:10)
    at Provider.module.exports.Provider.provide (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\service-hub\lib\provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\service-hub\lib\service-hub.js:50:18)
    at Package.activateServices (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js:441:44)
    at Package.activateNow (C:\Users\me\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js:247:14)```

### Which OS does this happen on?

🪟 Windows

### OS details

windows 10 pro 22H2 19045.2251

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Uninstall then reinstall git on local system and setup config as usual

## Demonstrate non-responsive git panel in editor

* Make change on local github repo and save.

Result: Git tab shows no changes, plus has no repo information in the statusbar

## Deactivate package

* open packages > Github 03611> Deactivate

Result: package deactivates

## Activate package

* Click Activate

Result: multiple errors are generated

### Additional Information:

I've attempted with multiple versions of Pulsar edit
When the statusbar options were available, I could click *Fetch* which bizarrely loaded the changed file so I could commit changes
Command line git works fine
Git apps such as Github desktop work fine

**Comment by ljsinclair** [comment]
## Update
I just installed Pulsar v 1.63.202212120804 and attempted to reactivate github.
No errors this time.
The treeview is highlighting a change however, but I don't believe this relates to this plugin
However it isn't recognising a github repository properly and is asking me to initialize.

Github desktop does recognise the repository

**Comment by fdarnel** [comment]
Same kind of error on v. 1.116.2024051323 arm64, macOS Sonoma.

Uncaught Error: Emitter has been disposed

/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:137
[Show Stack Trace](https://github.com/pulsar-edit/github/issues/5#)
The error was thrown from the [github package](https://github.com/pulsar-edit/github).
